cache: bundler
language: csharp
solution: DockerWebApp.sln
dotnet: 2.1.200
script:
  - dotnet build ./DockerWebApp/
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIGRNKQOQS54BI2LA
  secret_access_key:
    secure: "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"
  region: "us-east-1"  
  app: "TestApp"
  env: "Testapp-env"
  bucket_name: "btldemotestapp.s3-website-us-east-1.amazonaws.com"
deploy.skip_cleanup: true
after_success:
  - docker --version  # document the version travis is using
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - Invoke-Expression -Command (Get-ECRLoginCommand -Region us-east-1).Command
  - docker build -t docker_webapp .
  - docker tag docker_webapp:latest 912106457730.dkr.ecr.us-east-1.amazonaws.com/docker_webapp:latest
  - docker push 912106457730.dkr.ecr.us-east-1.amazonaws.com/docker_webapp:latest