version: '3.4'

services:
  dockerwebapp:
    image: dockerwebapp:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dockerwebapp$
    volumes:
      - c:\users\ashit.btl\source\repos\DockerWebApp\DockerWebApp:C:\app
      - C:\Users\Ashit.BTL\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_dockerwebapp$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dockerwebapp$ bin\\Debug\\netcoreapp2.0\\DockerWebApp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
